project:
  type: website

website:
  title: "Chicanery"
  favicon: static/inverted_icon.png
  sidebar:
    logo: static/icon.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: Tutorial
        href: wiki.qmd
        contents:
          - wiki/map.qmd
          - wiki/orders.qmd
          - wiki/units.qmd
          - wiki/research.qmd
          - wiki/tactics.qmd
      - section: Development
        href: dev-wiki.qmd
        contents:
          - dev-wiki/map.qmd
      - href: about.qmd
        text: About
  search:
    location: sidebar
    type: textbox
  page-footer:
    left:
      - "❤️ Chicanery, 2024"
      - icon: github
        href: https://github.com/tinskoric/chicanery
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: false
      
format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    html-table-processing: none
    grid:
      body-width: 1050px
    lightbox: true