project:
  type: website

website:
  title: "Chicanery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: wiki.qmd
        text: Wiki
      - href: about.qmd
        text: About

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

