project:
  type: website

website:
  title: "Chicanery Wiki"
  favicon: icon.png
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: wiki.qmd
        section: Tutorial
        contents:
          - wiki/map.qmd
          - wiki/orders.qmd
          - wiki/units.qmd
          - wiki/research.qmd
          - wiki/tactics.qmd
      - href: about.qmd
        text: About
  search:
    location: sidebar
    type: textbox
  page-footer:
    left: "❤️ Chicanery, 2024"
    right:
      - icon: github
        href: https://github.com/tinskoric/chicanery
  back-to-top-navigation: true
  page-navigation: true
      
format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

