---
title: "Orders and Economy"
---

------------------------------------------------------------------------

# Economy

In traditional (we're not talking about esoteric variants right now) Diplomacy, the player "economy" is extremely straightforward. There are a number of supply centers (centers hereafter) on the board based in cities. The number of centers you have defines how many units (referring to armies/fleets) you may build. In Chicanery, this relationship is abstracted.

In Chicanery, centers generate **income** (denoted, $I$, in included formulae) and **action points** (denoted AP hereafter) which serve dual functions. Income is used to *purchase* (and *replenish*, in the case of units) things like units, buildings, and "accoutrements"[^1] (discussed in the research subsection). AP are used to *order* units and (place) buildings. Income and AP are earned and accrued differently across turns and phases, illustrating the subtle difference in their functions. See the below sections for details:

[^1]: Chose a fancy-sounding word but its really just a research tree that gives some buffs to economic management and some useful tools for deceit/strategy.

## Income

Income is a linear function of the number of centers controlled between **turns**, earned at the start of the Spring phase (the start of a new turn), and available to be spent on various uses across all phases. Income is calculated purely by multiplying a scalar by the number of centers you possess (and adding bonuses from research).

| Phase | Description |
|----|----|
| Spring ($\pm$) | Income from centers held after the previous Fall phase is earned and added to the rolling total. Income can be spent on research (like replenishment cost buffs!) and research items. |
| Summer ($-$) | Income is spent on replenishing units. |
| Fall ($-$) | Income can be spent on research items. |
| Winter ($-$) | Income is spent on replenishing units. |
| Build ($-$) | Income is spent on purchasing new units and research items. |

: Income by Phase

Lastly, **income can be saved between phases and turns**. You will not lose the income you do not spend, it will roll over from one turn to the next. You **can** send other players a portion (or all) of your income.

## Action Points (AP)

AP are a decreasing function of the number of centers controlled between **phases**, earned at the start of the Spring and Fall phases, and available to be spent for use across all phases. AP is calculated by adding a fixed base number for a given number of centers and an exponentially decreasing function of your total center-count. As your state grows, the relative AP that you get from each center is less and less, constraining you opportunities for orders in each turn.

| Phase | Description |
|----|----|
| Spring ($\pm$) | AP from centers held after the previous Fall phase is earned. AP can be spent on issuing orders (attack, hold, support, convoy) to units. |
| Summer ($-$) | AP is spent on issuing retreat orders to units. |
| Fall ($\pm$) | AP from centers held after the Spring phase is earned. AP can be spent on issuing orders to units. |
| Winter ($-$) | AP is spent on issuing retreat orders to units. |
| Build ($-$) | AP is spent on placing new units and researched buildings—ports, supply hubs, and forts. |

: Action Points (AP) by Phase

If you gain/lose centers between the Spring and Fall phases, you will see the AP you earn in the latter phase altered, even if your opponent does not control that center for the whole turn.

> E.g., if you control a center at the outset of Spring `year-something` and someone else takes it in that turn, then in Fall `year-something`, your earned AP in the latter turn will not include AP that would've been earned from that center. Conversely, if you were the other player who gained it, your AP in the latter turn will include the income from that center.

Lastly, **AP can only be saved between phases**. You WILL lose the AP you do not spend between turns, it will **not** roll over from one year to the next. You **cannot** send other players your AP.

# Orders

So how do players interact with map elements? They issue orders!

-   Buildings and units can only be placed during the build phase.
